"""Nova card tabela

Revision ID: 573acd7e6b3d
Revises: ebdc1b42ac22
Create Date: 2025-05-13 13:37:59.058093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573acd7e6b3d'
down_revision = 'ebdc1b42ac22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('cvv', sa.String(length=4), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
